### ISSUE TITLE
Layout issue at sample download

### ISSUE THREAD

**Issue by jbgosset** [smartrank/lrmixstudio#4]
Hi,

We've got a layout issue, impossible to do anything right after having downloaded a profile:
![Lr-Mix Issue](https://user-images.githubusercontent.com/1073263/176213741-ac409bc0-5c17-4a2f-b859-0d6f74eadbfe.png)

We are using this java version:
![Lr-Mix Issue java version](https://user-images.githubusercontent.com/1073263/176213729-1572dd05-7113-4fbf-a45a-b82f6d963451.png)

Could you please have a look? Thanks you for your help.

**Comment by hyperjeroen** [comment]
Hi,

Funny, the controls seem to be superimposed on each other. This may
indicate direct-draw issue. I will try to reproduce this and let you know.

A couple of quick questions:
1. Is this the first time you are running lrmix studio on this machine, or
have you run it successfully before loading this sample?
2. Would it be possible to send me the sample file for testing purposes, or
is it case data (in which case i can image you would not be allowed to
share it)

I will keep you updated on.my efforts.

Kind regards,
Jeroen

Op di 28 jun. 2022 17:10 schreef Jean-Baptiste Gosset <
***@***.***>:

**Comment by jbgosset** [comment]
Hi,

Impossible to isolate the configuration to reproduce the bug. It seems to be related to network as depending on the PC's location we could make the issue disappear. But no mean to pin it down. So with the same sample file it can work or not on the same PC.

Thanks for trying,
